"""Ajout d'un blocage sur les threads

Revision ID: df14add2a1e9
Revises: 1c64e20b7a4a
Create Date: 2026-06-20 12:32:51.324288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df14add2a1e9'
down_revision: Union[str, Sequence[str], None] = '1c64e20b7a4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Rendre Nullable au débuts, apres rendre non nullables
    op.add_column('threads', sa.Column('is_currently_locked', sa.Boolean(), nullable=True))
    op.execute('UPDATE threads SET is_currently_locked = FALSE')
    op.alter_column('threads', 'is_currently_locked', nullable=False)
    op.create_index('idx_threads_is_locked', 'threads', ['is_currently_locked'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_threads_is_locked', table_name='threads')
    op.drop_column('threads', 'is_currently_locked')
    # ### end Alembic commands ###
