"""Ajout d'un index sur thread members

Revision ID: 1c64e20b7a4a
Revises: acbdec496ce4
Create Date: 2026-06-17 20:58:25.130956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c64e20b7a4a'
down_revision: Union[str, Sequence[str], None] = 'acbdec496ce4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_thread_members_thread_active', 'thread_members', ['thread_id'], unique=False, postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_thread_members_thread_active', table_name='thread_members', postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###
