"""Fix d'index pour paginations sur les messages

Revision ID: b56efa2fe563
Revises: 9beca0098794
Create Date: 2026-06-22 23:47:08.437875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b56efa2fe563'
down_revision: Union[str, Sequence[str], None] = '9beca0098794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_messages_thread_created'), table_name='messages')
    op.create_index('idx_messages_thread_created_id', 'messages', ['thread_id', 'created_at', 'id'], unique=False, postgresql_using='btree')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_messages_thread_created_id', table_name='messages', postgresql_using='btree')
    op.create_index(op.f('idx_messages_thread_created'), 'messages', ['thread_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
