"""Petites mascarades 2

Revision ID: 9beca0098794
Revises: 7bc763ffd740
Create Date: 2026-06-22 15:37:33.311694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9beca0098794'
down_revision: Union[str, Sequence[str], None] = '7bc763ffd740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_threads_wa_group_jid', 'threads', ['wa_group_jid'], unique=True)
    op.create_index('uq_threads_slug', 'threads', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_threads_slug', table_name='threads')
    op.drop_index('uq_threads_wa_group_jid', table_name='threads')
    # ### end Alembic commands ###
