"""Retrait de faux unique

Revision ID: acbdec496ce4
Revises: b61d515be67a
Create Date: 2026-06-17 00:15:44.063771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acbdec496ce4'
down_revision: Union[str, Sequence[str], None] = 'b61d515be67a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('members_wa_jid_key'), 'members', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('members_wa_jid_key'), 'members', ['wa_jid'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
