"""xxxx

Revision ID: b61d515be67a
Revises: b430c46e0279
Create Date: 2026-06-17 00:13:35.971579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b61d515be67a'
down_revision: Union[str, Sequence[str], None] = 'b430c46e0279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('threads_slug_key'), 'threads', type_='unique')
    op.drop_constraint(op.f('threads_wa_group_jid_key'), 'threads', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('threads_wa_group_jid_key'), 'threads', ['wa_group_jid'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('threads_slug_key'), 'threads', ['slug'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
