"""Petites mascarades

Revision ID: 7bc763ffd740
Revises: df14add2a1e9
Create Date: 2026-06-22 15:36:04.954791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bc763ffd740'
down_revision: Union[str, Sequence[str], None] = 'df14add2a1e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_threads_slug'), table_name='threads')
    op.drop_index(op.f('uq_threads_wa_group_jid'), table_name='threads')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_threads_wa_group_jid'), 'threads', ['wa_group_jid'], unique=True)
    op.create_index(op.f('uq_threads_slug'), 'threads', ['slug'], unique=True)
    # ### end Alembic commands ###
