class ServicesNames:
    USER_SERVICE = "USER_SERVICE"
    SESSION_SERVICE = "SESSION_SERVICE"
    UNKNOWN_SERVICE = "UNKNOWN_SERVICE"
    AUTH_SERVICE = "AUTH_SERVICE"
    THREAD_SERVICE = "THREAD_SERVICE"
    MESSAGE_SERVICE = "MESSAGE_SERVICE"
    MEMBER_SERVICE = "MEMBER_SERVICE"
